<<<<<<< HEAD
kof.version=0.2.0-beta
kof.compiler.version=0.1.11
kof.runtime.version=0.1.11
kof.stdlib.version=0.1.11
=======
kof.version=0.2.0-beta
kof.compiler.version=0.2.0
kof.runtime.version=0.2.0
kof.stdlib.version=0.2.0
>>>>>>> 92f319f (build: bump version to 0.2.0-beta [skip ci])
kof.tooling.api=21
